#!/usr/bin/env bash

################################################################################
# Runs all checks on the repository
#
# Usage:
#     ./check/all
################################################################################

# Get the working directory to the repo root.
cd "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$(git rev-parse --show-toplevel)"

# tests are ordered based on importance (e.g. when format fails, it often means
# there is a syntax error) and speed (slow checks last)
echo "Running format check"
check/format || exit 1  # this syntax causes whole script to terminate if format fails
echo "Running flake8 check"
check/flake8
echo "Running type check"
check/mypy
echo "Running lint check on changed files"
check/pylint-changed-files
#echo "Running pytest and coverage checks"
#check/coverage
#echo "Running build docs check"
#dev_tools/build_docs
